spring:
  application:
    name: core-api

security:
  oauth2:
    resource:
      access-token-uri: ${AUTHORIZATION_HOST:http://localhost:9191}/oauth/token
      token-info-uri: ${AUTHORIZATION_HOST:http://localhost:9191}/oauth/check_token
    client:
      client-id: mobile
      client-secret: pin

axon:
  eventhandling:
    processors:
      MakeTransactionSagaProcessor:
        mode: subscribing
  axonserver:
    servers: ${AXON_SERVER:localhost}



